<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Product>RusysDev.LaikoLimitas.0.3</Product>
		<AssemblyName>LaikoLimitas</AssemblyName>
		<AssemblyTitle>Laiko Limitas</AssemblyTitle>
		<ApplicationIcon>icon.ico</ApplicationIcon>
		<PublishSingleFile>true</PublishSingleFile>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
	</PropertyGroup>


	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>none</DebugType>
	</PropertyGroup>


	<ItemGroup>
		<Folder Include="images\" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="images\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Pack>true</Pack>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Content Include="icon.ico" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Shared\Shared.csproj" />
	</ItemGroup>


</Project>
